#version 450

#define TILE_DIM 16
layout(local_size_x = TILE_DIM, local_size_y = TILE_DIM, local_size_z = 1) in;

layout(binding = 0) readonly buffer MatrixA {
    float elements[];
} matrixA;

layout(binding = 1) readonly buffer MatrixB {
    float elements[];
} matrixB;

layout(binding = 2) writeonly buffer MatrixC {
    float elements[];
} matrixC;

layout(push_constant) uniform PushConstants {
    uint N;
    uint M;
    uint K;
    uint baseWorkgroupX;
    uint baseWorkgroupY;
} pc;

shared float tileA[TILE_DIM][TILE_DIM];
shared float tileB[TILE_DIM][TILE_DIM];

void main() {
    const uint globalRow =
        pc.baseWorkgroupY * TILE_DIM + gl_GlobalInvocationID.y;
    const uint globalColumn =
        pc.baseWorkgroupX * TILE_DIM + gl_GlobalInvocationID.x;
    const uint localRow = gl_LocalInvocationID.y;
    const uint localColumn = gl_LocalInvocationID.x;

    float sum = 0.0;
    const uint tileCount = (pc.K + TILE_DIM - 1) / TILE_DIM;

    for (uint tile = 0; tile < tileCount; ++tile) {
        const uint aColumn = tile * TILE_DIM + localColumn;
        const uint bRow = tile * TILE_DIM + localRow;

        tileA[localRow][localColumn] =
            (globalRow < pc.N && aColumn < pc.K)
                ? matrixA.elements[globalRow * pc.K + aColumn]
                : 0.0;
        tileB[localRow][localColumn] =
            (bRow < pc.K && globalColumn < pc.M)
                ? matrixB.elements[bRow * pc.M + globalColumn]
                : 0.0;

        barrier();
        for (uint k = 0; k < TILE_DIM; ++k) {
            sum += tileA[localRow][k] * tileB[k][localColumn];
        }
        barrier();
    }

    if (globalRow < pc.N && globalColumn < pc.M) {
        matrixC.elements[globalRow * pc.M + globalColumn] = sum;
    }
}